### ISSUE TITLE
Unable to add Mle configuration to existing project

### ISSUE THREAD

**Issue by fewtrees** [machaval/mule-intellij-plugins#110]
null
java.lang.NullPointerException
	at org.mule.tooling.esb.framework.MuleFrameworkConfigurable.addSupport(MuleFrameworkConfigurable.java:51)
	at com.intellij.framework.addSupport.impl.AddSupportForSingleFrameworkDialog$2.run(AddSupportForSingleFrameworkDialog.java:130)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.application.WriteAction.execute(WriteAction.java:38)
	at com.intellij.framework.addSupport.impl.AddSupportForSingleFrameworkDialog.addSupport(AddSupportForSingleFrameworkDialog.java:133)
	at com.intellij.framework.addSupport.impl.AddSupportForSingleFrameworkDialog.doOKAction(AddSupportForSingleFrameworkDialog.java:90)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1867)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1828)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:736)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:458)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1686)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1650)
	at org.mule.tooling.esb.framework.MuleFrameworkDetector$MuleFrameworkDetected$1.run(MuleFrameworkDetector.java:141)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by javaduke** [comment]
Can you please help me understand how do I reproduce this issue? Can you provide the step-by-step direction?

**Comment by fewtrees** [comment]
Hi,

I had an existing mule app that was created with AnyPointStudio that is based on a 3.8.5 runtime.

In IntelliJ you create a new maven project based on the mule apps pom.xml. This works fine as there’s no facet configuration going on..
Then IntelliJ recognises with your plugin recognises it’s a mule and and shows the configuration dialog box
I have to select a mule CE runtime 3.8.1 and click OK where nothing happens.
Then I click cancel and that when you get the error.

Hope this helps..

Robert Smallwood | Senior Java Dev
Fewtrees Media Ltd
m: +44 (0)7971 652616, e: rob@fewtrees.com

**Comment by javaduke** [comment]
Ah, interesting, thank you for this information, I'll try to reproduce it and see if it can be easily fixed. The truth is that I've never tested the plugin with Mule CE, so it could be that it is not 100% supported.

**Comment by javaduke** [comment]
I tried but was unable to reproduce the issue. I downloaded and installed Mule CE 3.8.1 on my laptop. Then I created a Maven-based project outside of IntelliJ and imported it using New Project From Existing Sources command. After importing, IntelliJ recognized the Mule app and showed the SDK selection dialog. I created new SDK based on 3.8.1 and selected it. Everything worked as expected. I used the latest version of IntelliJ CE 2017.2.5 and the latest version of the Mule plugin 0.13.

**Comment by fewtrees** [comment]
I’ll send screenshots..

1. Maven project with a mule-project.xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mule-project xmlns="http://www.mulesoft.com/tooling/project" runtimeId="org.mule.tooling.server.3.8.4.ee" schemaVersion="5.3.0.0">
    <name>myfarm</name>
    <description></description>
</mule-project>

2. IntelliJ picks up this is a Mule project




3. Click Configure


3. Click ‘OK’


This is the default library that is shown..

Just to check that’s ok - I click ‘Configure’ and it shows..


All seems fine so I click ‘Cancel’ and back at the below screen I click ‘OK’..

.. nothing happens.. At this point I expected something to happen but it doesn’t.

 So I then click ‘Cancel’ to exit the dialog box and the following appears..


Regards,

Robert Smallwood | Senior Java Dev
Fewtrees Media Ltd
m: +44 (0)7971 652616, e: rob@fewtrees.com

**Comment by fewtrees** [comment]
BTW This issue is on Mac OSX10.12.6

**Comment by javaduke** [comment]
Sorry, I don't see any screenshots here...

**Comment by javaduke** [comment]
I was finally able to reproduce the problem, I'm working on a fix.

**Comment by javaduke** [comment]
I think I was able to reproduce the problem, but only on one of my environments, the other one is still working correctly. Can you please upload your screenshots somewhere, where I can see them? I just want to make sure I'm taking right steps to reproduce the issue. It seems like for some reason you have what IntelliJ thinks is a Mule library, but it does not have an SDK configured.

**Comment by javaduke** [comment]
I have an update - apparently it works differently in IDEA 2017.2, that's why I was unable to reproduce. Which version of IDEA do you have?

**Comment by fewtrees** [comment]
Hi,

My build is 2017.2.5 on Mac

Cheers Rob

**Comment by fewtrees** [comment]
Screenshots in this album..

https://flic.kr/s/aHsm4S6TDP <https://flic.kr/s/aHsm4S6TDP>

**Comment by javaduke** [comment]
Hmmm, there's clearly something I'm missing. I was able to reproduce it on 2017.1 and then I upgraded to 2017.2.5 and the upgrade fixed it. I added the null check to avoid the NPE, but the MULE_HOME would still be null.
