### ISSUE TITLE
NPE when Run Config is created and launched for the first time

### ISSUE THREAD

**Issue by javaduke** [machaval/mule-intellij-plugins#21]
java.lang.NullPointerException
	at org.mule.launcher.configuration.archive.MuleAppMavenHandler.getMuleApp(MuleAppMavenHandler.java:22)
	at org.mule.launcher.configuration.archive.MuleAppManager.getMuleApp(MuleAppManager.java:29)
	at org.mule.launcher.configuration.runner.MuleRunnerCommandLine.deployApp(MuleRunnerCommandLine.java:118)
	at org.mule.launcher.configuration.runner.MuleRunnerCommandLine.startProcess(MuleRunnerCommandLine.java:112)
	at org.mule.launcher.configuration.runner.MuleRunnerCommandLine.startProcess(MuleRunnerCommandLine.java:25)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgramRunner.java:81)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:389)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:161)
	at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:346)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by machaval** [comment]
I think is fixed will close it and if you still can reproduce it reopen with new stack trace and steps to reproduce
