### ISSUE TITLE
IDEA 2016.2 community edn - exceptions on startup with RAML plugin

### ISSUE THREAD

**Issue by rm-hull** [machaval/mule-intellij-plugins#46]
With: 

IntelliJ IDEA 2016.2.4
Build #IC-162.2032.8, built on September 9, 2016
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

On starting, get the following 'IDE Fatal Errors' message

<img width="1039" alt="screen shot 2016-09-22 at 10 29 58" src="https://cloud.githubusercontent.com/assets/1915543/18743131/8abf7c12-80af-11e6-83da-5aac14cc3e68.png">

The exception stack trace:

```
Expecting SimpleTypeNode but got class org.raml.v2.internal.framework.nodes.snakeyaml.SYNullNode
java.lang.RuntimeException: Expecting SimpleTypeNode but got class org.raml.v2.internal.framework.nodes.snakeyaml.SYNullNode
	at org.raml.v2.internal.framework.nodes.AbstractReferenceNode.getParameters(AbstractReferenceNode.java:91)
	at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsTransformer.applyResourceType(ResourceTypesTraitsTransformer.java:156)
	at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsTransformer.transform(ResourceTypesTraitsTransformer.java:91)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:45)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:86)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:71)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:110)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:98)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:93)
	at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:36)
	at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:17)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by machaval** [comment]
Can you send me the raml tha causes this issue?

**Comment by rm-hull** [comment]
> Can you send me the raml tha causes this issue?

possibly not, unfortunately - it is for a gov project.

it is a RAML1.0 project, there are lots of includes, annotations, libraries.

I notice your [grade build script](https://github.com/machaval/mule-intellij-plugins/blob/master/raml-plugin/build.gradle#L13) uses a snapshot version of raml-parser-2: We use _org.raml:raml-parser-2:1.0.0_ jar and all the docs parse successfully using that (with the `RamlModelBuilder` class).

**Comment by machaval** [comment]
Ok good I'm releasing a new version of the editor soon with the latest
parser this should fix your issue
