### ISSUE TITLE
AbstractMethodError when resuming

### ISSUE THREAD

**Issue by machaval** [machaval/mule-intellij-plugins#55]
java.lang.AbstractMethodError
    at com.intellij.xdebugger.XDebugProcess.resume(XDebugProcess.java:194)
    at org.mule.tooling.esb.debugger.ContextAwareDebugProcess.resume(ContextAwareDebugProcess.java:114)
    at com.intellij.xdebugger.XDebugProcess.resume(XDebugProcess.java:203)
    at com.intellij.xdebugger.impl.XDebugSessionImpl.resume(XDebugSessionImpl.java:541)
    at com.intellij.xdebugger.impl.XDebuggerSupport$6.perform(XDebuggerSupport.java:105)
    at com.intellij.xdebugger.impl.actions.handlers.XDebuggerActionHandler.perform(XDebuggerActionHandler.java:34)
    at com.intellij.xdebugger.impl.actions.XDebuggerActionBase.a(XDebuggerActionBase.java:100)
    at com.intellij.xdebugger.impl.actions.XDebuggerActionBase.performWithHandler(XDebuggerActionBase.java:92)
    at com.intellij.xdebugger.impl.actions.ResumeAction.actionPerformed(ResumeAction.java:47)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:188)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:154)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:325)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)

**Comment by javaduke** [comment]
Well, that explains it:
@Deprecated
    public void resume() {
        throw new AbstractMethodError();
    }
There's a bunch of deprecated methods in the XDebugProcess class. I'll work it tomorrow.
