### ISSUE TITLE
Running integration with Mule Batch causes exception

### ISSUE THREAD

**Issue by jeffbowman** [machaval/mule-intellij-plugins#88]
I have a project that needed data between 2 different databases on different hosts, created a migration to move data from one to the other using Mule Batch. I get the following error which this post from StackOverflow indicates was related to a bug fixed in 3.5.3 and the work around in AnypointStudio is to make sure to click the 'Always' button for clearing application data, but there seems to be no way to do this from the (awesome!) IntelliJ plugins. 

StackOverflow link: http://stackoverflow.com/questions/30879937/mule-batch-negative-seek-offset-illegalaccesserror-sun-nio-cs-utf-8

ERROR 2017-05-04 14:56:52,055 [batch-job-migrate-data-batch-work-manager.01] com.mulesoft.module.batch.engine.threading.BatchRecordWork: Exception found while processing block 'd0ba9080-3103-11e7-b253-6a6114123086' for instance '33987970-30f9-11e7-a1f1-6a6114123086' of batch job 'migrate-data-batch'. Records will be queued back
java.lang.IllegalAccessError: tried to access class sun.nio.cs.UTF_8 from class sun.nio.cs.UTF_8ConstructorAccess
	at sun.nio.cs.UTF_8ConstructorAccess.newInstance(Unknown Source) ~[kryo-shaded-3.0.3.jar:1.7.0_80]
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy$1.newInstance(Kryo.java:1237) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1090) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:570) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:546) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40) ~[kryo-shaded-3.0.3.jar:?]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790) ~[kryo-shaded-3.0.3.jar:?]
	at com.mulesoft.module.serialization.kryo.internal.KryoObjectSerializer.doDeserialize(KryoObjectSerializer.java:117) ~[mule-module-kryo-serializer-ee-3.8.4.jar:3.8.4]
	at org.mule.serialization.internal.AbstractObjectSerializer.deserialize(AbstractObjectSerializer.java:135) ~[mule-core-3.8.4.jar:3.8.4]
	at org.mule.serialization.internal.AbstractObjectSerializer.deserialize(AbstractObjectSerializer.java:112) ~[mule-core-3.8.4.jar:3.8.4]
	at org.mule.serialization.internal.AbstractObjectSerializer.deserialize(AbstractObjectSerializer.java:102) ~[mule-core-3.8.4.jar:3.8.4]
	at com.mulesoft.module.batch.engine.queue.AbstractBatchQueueDelegate.poll(AbstractBatchQueueDelegate.java:159) ~[mule-module-batch-ee-3.8.4.jar:3.8.4]
	at com.mulesoft.module.batch.engine.threading.BatchRecordWork.run(BatchRecordWork.java:60) ~[mule-module-batch-ee-3.8.4.jar:3.8.4]
	at org.mule.work.WorkerContext.run(WorkerContext.java:301) ~[mule-core-3.8.4.jar:3.8.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

**Comment by javaduke** [comment]
Good idea, I'll see what I can do. For now you can simply delete your $MULE_HOME/.mule/<app-name> directory before you run your app.

**Comment by javaduke** [comment]
Clean App Data functionality implemented in Run Configuration.
