### ISSUE TITLE
Wrong line separators

### ISSUE THREAD

**Issue by chka73** [machaval/mule-intellij-plugins#95]
Got an error report from Idea.

```
Wrong line separators: '...0123*0*P*~\r\nGS*SH*GN...' at offset 124
java.lang.AssertionError: Wrong line separators: '...0123*0*P*~\r\nGS*SH*GN...' at offset 124
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2605)
	at com.intellij.openapi.editor.impl.DocumentImpl.b(DocumentImpl.java:622)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:544)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:975)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:980)
	at org.mule.tooling.lang.dw.editor.WeaveEditor.runPreview(WeaveEditor.java:493)
	at org.mule.tooling.lang.dw.editor.WeaveEditor$1$1$1.run(WeaveEditor.java:201)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:234)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:171)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:170)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:119)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:212)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:168)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:151)
	at org.mule.tooling.lang.dw.editor.WeaveEditor$1$1.run(WeaveEditor.java:203)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.AssertionError: Wrong line separators: '...0123*0*P*~\r\nGS*SH*GN...' at offset 124
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2605)
	at com.intellij.openapi.editor.impl.DocumentImpl.b(DocumentImpl.java:622)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:544)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:975)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:980)
	at org.mule.tooling.lang.dw.editor.WeaveEditor.runPreview(WeaveEditor.java:493)
	at org.mule.tooling.lang.dw.editor.WeaveEditor$1$1$1.run(WeaveEditor.java:201)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:234)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:171)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:170)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:119)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:212)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:168)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:151)
	at org.mule.tooling.lang.dw.editor.WeaveEditor$1$1.run(WeaveEditor.java:203)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.AssertionError: Wrong line separators: '...0123*0*P*~\r\nGS*SH*GN...' at offset 124
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2605)
	at com.intellij.openapi.editor.impl.DocumentImpl.b(DocumentImpl.java:622)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:544)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:975)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:980)
	at org.mule.tooling.lang.dw.editor.WeaveEditor.runPreview(WeaveEditor.java:493)
	at org.mule.tooling.lang.dw.editor.WeaveEditor$1$1$1.run(WeaveEditor.java:201)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:234)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:171)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:170)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:119)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:212)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:168)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:151)
	at org.mule.tooling.lang.dw.editor.WeaveEditor$1$1.run(WeaveEditor.java:203)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

**Comment by javaduke** [comment]
Can you please attach your DW script and the sample input to this ticket?

**Comment by chka73** [comment]
Dataweave
```%dw 1.0
%input payload application/xml
%output application/xml
---
{
    instruction: {
        header: {
            version: '1.0',
            sender @(id: '${senderId}', codelist: 30): {},
            receiver @(id: '${receiverId}', codelist: 30): {},
            interchangetime: now as :string {format: "EEE, dd MMM yyyy HH:mm:ss Z"},
            interchangeid: flowVars.interchangeId,
            application @(id: 1000, name: 'GIB', version: '1.0'): {}
        },
        (payload.*Shipment.*ShipmentUnit map
                using (
                    shipDate = payload.Shipment.ShipmentHeader.ActualShipDateTime as :datetime as :string {format: "yyyyMMddHHmm"},
                    proNo = payload.Shipment.ShipmentHeader.CarrierParty.UserArea.*Note[?($.@type == "proNo")][0],
                    shipToParty = payload.Shipment.ShipmentHeader.ShipToParty,
                    customer = payload.Shipment.ShipmentHeader.ShipToParty
                )
            {
            consignment @(functioncode:9): {
                date @(type: 'SHIP'): shipDate,
                service @(code:'15'): {},
                reference @(type:'CU'): proNo when proNo != null and proNo != '' otherwise 'NULL',
                consignor @(id:'0410096713', name: p('name')):{
                    address:
                        {street: p('consignor.DK.street'),
                        postcode: p('consignor.DK.postcode'),
                        city: p('consignor.DK.city'),
                        countrycode: p('consignor.DK.countrycode')} when shipToParty.Location.Address.CountryCode == 'DK' otherwise
                        (
                        {street: p('consignor.FI.street'),
                        postcode: p('consignor.FI.postcode'),
                        city: p('consignor.FI.city'),
                        countrycode: p('consignor.FI.countrycode')} when shipToParty.Location.Address.CountryCode == 'FI' otherwise
                            (
                        {street: p('consignor.SE.street'),
                        postcode: p('consignor.SE.postcode'),
                        city: p('consignor.SE.city'),
                        countrycode: p('consignor.SE.countrycode')} when shipToParty.Location.Address.CountryCode == 'SE' otherwise
                        {street: {},
                         postcode: {},
                         city: {},
                         countrycode: {}}
                            )
                        )
                },
                consignee @(name: customer.Location.Address.*AddressLine[0]): {
                    address: {
                        street: customer.Location.Address.*AddressLine[1],
                        postcode: customer.Location.Address.PostalCode replace " " with "",
                        city: customer.Location.Address.CityName,
                        countrycode: customer.Location.Address.CountryCode
                    }
                },
                ($.*ShipmentUnitItem groupBy $.UserArea.Note pluck
                    (parcel @(id: leftPad($.UserArea.Note[0], 20, '0')): {}) when $.UserArea.Note[0].@type == 'parcelId'
                )
            }
        })
    }
}
```

XML input
```
<?xml version="1.0" encoding="UTF-8"?>
<ns0:Request xmlns:ns0="http://esb.uti.com/EnterpriseMessage_2.6">
    <ns1:Header
            xmlns:ns1="http://esb.uti.com/EnterpriseMessage_2.6" xmlns:ns0="http://www.uti.com/sce/OutboundRequest"
    >
        <ns1:CallerID>Caller01</ns1:CallerID>
        <ns1:CorrelationID>0b-aae2-240042ed61cd</ns1:CorrelationID>
        <ns1:TransactionID>0000192793</ns1:TransactionID>
        <ns1:Timestamp>2017-03-27T22:22:54.507+02:00</ns1:Timestamp>
        <ns1:InterfaceID>ShipmentOrder</ns1:InterfaceID>
        <ns1:RoutingID>INT015_LoadShippedOrganization</ns1:RoutingID>
        <ns1:MessageID>Load ID:0000192793</ns1:MessageID>
        <ns1:Division>CLD</ns1:Division>
        <ns1:TransactionType>loadshipped</ns1:TransactionType>
    </ns1:Header>
    <ns1:Shipment xmlns:ns1="http://www.uti.com/sce/Shipment_2.6">
        <ns1:RequestType>Event</ns1:RequestType>
        <ns1:Action>LoadShipped</ns1:Action>
        <ns1:ShipmentHeader>
            <ns1:Owner/>
            <ns1:DocumentID>0000016461</ns1:DocumentID>
            <ns1:ExternalDocumentID>FC33757-06</ns1:ExternalDocumentID>
            <ns1:Type>15</ns1:Type>
            <ns1:ShipFromParty>
                <ns1:Address>
                    <ns1:AddressLine/>
                    <ns1:AddressLine/>
                    <ns1:AddressLine/>
                    <ns1:AddressLine/>
                    <ns1:City/>
                    <ns1:Country/>
                    <ns1:CountryCode/>
                </ns1:Address>
            </ns1:ShipFromParty>
            <ns1:Load>
                <ns1:DocumentID>0000192793</ns1:DocumentID>
                <ns1:TransportationTerms/>
            </ns1:Load>
            <ns1:Carrier>
                <ns1:CarrierParty>
                    <ns1:Name>CarrierParcel</ns1:Name>
                </ns1:CarrierParty>
                <ns1:TrailerInfo>
                    <ns1:TrailerNo/>
                    <ns1:Description>AIR</ns1:Description>
                    <ns1:PRONo>42604620000000297</ns1:PRONo>
                </ns1:TrailerInfo>
            </ns1:Carrier>
            <ns1:ShipToParty>
                <ns1:Name></ns1:Name>
                <ns1:Address>
                    <ns1:AddressLine>Some Store</ns1:AddressLine>
                    <ns1:AddressLine>Street 15</ns1:AddressLine>
                    <ns1:AddressLine/>
                    <ns1:AddressLine/>
                    <ns1:City>CITY</ns1:City>
                    <ns1:Country>SWEDEN</ns1:Country>
                    <ns1:CountryCode>SE</ns1:CountryCode>
                    <ns1:Postcode>13875</ns1:Postcode>
                </ns1:Address>
                <ns1:Contact>
                    <ns1:Email/>
                    <ns1:Tel>
                        <ns1:Type>TelNumber</ns1:Type>
                        <ns1:Number>+4687654321</ns1:Number>
                    </ns1:Tel>
                </ns1:Contact>
            </ns1:ShipToParty>
            <ns1:DateTimeRefs>
                <ns1:Type>Load Add Date</ns1:Type>
                <ns1:DateTime>2017-02-16T15:07:00.520+0100</ns1:DateTime>
            </ns1:DateTimeRefs>
            <ns1:DateTimeRefs>
                <ns1:Type>ACTUALSHIPDATE</ns1:Type>
                <ns1:DateTime>2017-02-16T15:11:03.703+0100</ns1:DateTime>
            </ns1:DateTimeRefs>
            <ns1:DateTimeRefs>
                <ns1:Type>ACTUALARRIVALDATE</ns1:Type>
                <ns1:DateTime>2017-02-16T15:07:00.520+0100</ns1:DateTime>
            </ns1:DateTimeRefs>
            <ns1:References>
                <ns1:ID>1</ns1:ID>
                <ns1:Type>RetrunsTrackingNo</ns1:Type>
                <ns1:Value/>
            </ns1:References>
            <ns1:ExtendedFields>
                <ns1:ID>1</ns1:ID>
                <ns1:Type>Seal</ns1:Type>
                <ns1:Value/>
            </ns1:ExtendedFields>
            <ns1:ExtendedFields>
                <ns1:ID>2</ns1:ID>
                <ns1:Type>BUYERPO</ns1:Type>
                <ns1:Value>33757</ns1:Value>
            </ns1:ExtendedFields>
            <ns1:ShipmentDetail>
                <ns1:ExternalLineNumber/>
                <ns1:ItemID>1512533-311-46</ns1:ItemID>
                <ns1:Lottable>
                    <ns1:Lottables>
                        <ns1:Type>lottable02</ns1:Type>
                        <ns1:Value></ns1:Value>
                    </ns1:Lottables>
                </ns1:Lottable>
                <ns1:Quantities>
                    <ns1:Type>SHIPPEDQTY</ns1:Type>
                    <ns1:Amount>1</ns1:Amount>
                </ns1:Quantities>
                <ns1:ExtendedFields>
                    <ns1:ID>1</ns1:ID>
                    <ns1:Type>DropID</ns1:Type>
                    <ns1:Value>0000016461-001</ns1:Value>
                </ns1:ExtendedFields>
            </ns1:ShipmentDetail>
            <ns1:ShipmentDetail>
                <ns1:ExternalLineNumber/>
                <ns1:ItemID>1512533-311-48</ns1:ItemID>
                <ns1:Lottable>
                    <ns1:Lottables>
                        <ns1:Type>lottable02</ns1:Type>
                        <ns1:Value></ns1:Value>
                    </ns1:Lottables>
                </ns1:Lottable>
                <ns1:Quantities>
                    <ns1:Type>SHIPPEDQTY</ns1:Type>
                    <ns1:Amount>1</ns1:Amount>
                </ns1:Quantities>
                <ns1:ExtendedFields>
                    <ns1:ID>1</ns1:ID>
                    <ns1:Type>DropID</ns1:Type>
                    <ns1:Value>0000016461-001</ns1:Value>
                </ns1:ExtendedFields>
            </ns1:ShipmentDetail>
            <ns1:ShipmentDetail>
                <ns1:ExternalLineNumber/>
                <ns1:ItemID>1512533-311-50</ns1:ItemID>
                <ns1:Lottable>
                    <ns1:Lottables>
                        <ns1:Type>lottable02</ns1:Type>
                        <ns1:Value></ns1:Value>
                    </ns1:Lottables>
                </ns1:Lottable>
                <ns1:Quantities>
                    <ns1:Type>SHIPPEDQTY</ns1:Type>
                    <ns1:Amount>4</ns1:Amount>
                </ns1:Quantities>
                <ns1:ExtendedFields>
                    <ns1:ID>1</ns1:ID>
                    <ns1:Type>DropID</ns1:Type>
                    <ns1:Value>0000016461-001</ns1:Value>
                </ns1:ExtendedFields>
            </ns1:ShipmentDetail>
        </ns1:ShipmentHeader>
        <ns1:ShipmentHeader>
            <ns1:Owner/>
            <ns1:DocumentID>0000016462</ns1:DocumentID>
            <ns1:ExternalDocumentID>SE-191529</ns1:ExternalDocumentID>
            <ns1:Type>15</ns1:Type>
            <ns1:Load>
                <ns1:DocumentID>0000192793</ns1:DocumentID>
                <ns1:TransportationTerms/>
            </ns1:Load>
            <ns1:Carrier>
                <ns1:CarrierParty>
                    <ns1:Name>CarrierParcel</ns1:Name>
                </ns1:CarrierParty>
                <ns1:TrailerInfo>
                    <ns1:TrailerNo/>
                    <ns1:Description>AIR</ns1:Description>
                    <ns1:PRONo>42604620000000297</ns1:PRONo>
                </ns1:TrailerInfo>
            </ns1:Carrier>
            <ns1:ShipToParty>
                <ns1:Name></ns1:Name>
                <ns1:Address>
                    <ns1:AddressLine>Some Store</ns1:AddressLine>
                    <ns1:AddressLine>Street 15</ns1:AddressLine>
                    <ns1:AddressLine/>
                    <ns1:AddressLine/>
                    <ns1:City>CITY</ns1:City>
                    <ns1:Country>SWEDEN</ns1:Country>
                    <ns1:CountryCode>SE</ns1:CountryCode>
                    <ns1:Postcode>18654</ns1:Postcode>
                </ns1:Address>
                <ns1:Contact>
                    <ns1:Email/>
                    <ns1:Tel>
                        <ns1:Type>TelNumber</ns1:Type>
                        <ns1:Number>+4681234567</ns1:Number>
                    </ns1:Tel>
                </ns1:Contact>
            </ns1:ShipToParty>
            <ns1:DateTimeRefs>
                <ns1:Type>Load Add Date</ns1:Type>
                <ns1:DateTime>2017-02-16T15:07:00.520+0100</ns1:DateTime>
            </ns1:DateTimeRefs>
            <ns1:DateTimeRefs>
                <ns1:Type>ACTUALSHIPDATE</ns1:Type>
                <ns1:DateTime>2017-02-16T15:11:03.703+0100</ns1:DateTime>
            </ns1:DateTimeRefs>
            <ns1:DateTimeRefs>
                <ns1:Type>ACTUALARRIVALDATE</ns1:Type>
                <ns1:DateTime>2017-02-16T15:07:00.520+0100</ns1:DateTime>
            </ns1:DateTimeRefs>
            <ns1:References>
                <ns1:ID>1</ns1:ID>
                <ns1:Type>ReturnsTrackingNo</ns1:Type>
                <ns1:Value/>
            </ns1:References>
            <ns1:ExtendedFields>
                <ns1:ID>1</ns1:ID>
                <ns1:Type>Seal</ns1:Type>
                <ns1:Value/>
            </ns1:ExtendedFields>
            <ns1:ExtendedFields>
                <ns1:ID>2</ns1:ID>
                <ns1:Type>BUYERPO</ns1:Type>
                <ns1:Value>33757</ns1:Value>
            </ns1:ExtendedFields>
            <ns1:ShipmentDetail>
                <ns1:ExternalLineNumber/>
                <ns1:ItemID>1512533-311-46</ns1:ItemID>
                <ns1:Lottable>
                    <ns1:Lottables>
                        <ns1:Type>lottable02</ns1:Type>
                        <ns1:Value></ns1:Value>
                    </ns1:Lottables>
                </ns1:Lottable>
                <ns1:Quantities>
                    <ns1:Type>SHIPPEDQTY</ns1:Type>
                    <ns1:Amount>1</ns1:Amount>
                </ns1:Quantities>
                <ns1:ExtendedFields>
                    <ns1:ID>1</ns1:ID>
                    <ns1:Type>DropID</ns1:Type>
                    <ns1:Value>0000016461-001</ns1:Value>
                </ns1:ExtendedFields>
            </ns1:ShipmentDetail>
            <ns1:ShipmentDetail>
                <ns1:ExternalLineNumber/>
                <ns1:ItemID>1512533-311-48</ns1:ItemID>
                <ns1:Lottable>
                    <ns1:Lottables>
                        <ns1:Type>lottable02</ns1:Type>
                        <ns1:Value></ns1:Value>
                    </ns1:Lottables>
                </ns1:Lottable>
                <ns1:Quantities>
                    <ns1:Type>SHIPPEDQTY</ns1:Type>
                    <ns1:Amount>1</ns1:Amount>
                </ns1:Quantities>
                <ns1:ExtendedFields>
                    <ns1:ID>1</ns1:ID>
                    <ns1:Type>DropID</ns1:Type>
                    <ns1:Value>373500454541021022</ns1:Value>
                </ns1:ExtendedFields>
            </ns1:ShipmentDetail>
            <ns1:ShipmentDetail>
                <ns1:ExternalLineNumber/>
                <ns1:ItemID>1512533-311-50</ns1:ItemID>
                <ns1:Lottable>
                    <ns1:Lottables>
                        <ns1:Type>lottable02</ns1:Type>
                        <ns1:Value></ns1:Value>
                    </ns1:Lottables>
                </ns1:Lottable>
                <ns1:Quantities>
                    <ns1:Type>SHIPPEDQTY</ns1:Type>
                    <ns1:Amount>4</ns1:Amount>
                </ns1:Quantities>
                <ns1:ExtendedFields>
                    <ns1:ID>1</ns1:ID>
                    <ns1:Type>DropID</ns1:Type>
                    <ns1:Value>373500454541021023</ns1:Value>
                </ns1:ExtendedFields>
            </ns1:ShipmentDetail>
        </ns1:ShipmentHeader>
    </ns1:Shipment>
</ns0:Request>
```

**Comment by javaduke** [comment]
Hmm, either the DW your posted or the XML is not correct - the DW expects `payload.*Shipment.*ShipmentUnit` but there are no `ShipmentUnit` elements in this XML.

**Comment by chka73** [comment]
Ok.
Saw now that I got the incorrect XML file.
But that doesn't change the error message.
Try this one instead:

```
<?xml version="1.0" encoding="UTF-8"?>
<ProcessShipment xmlns="http://www.openapplications.org/oagis/9" releaseID="1">
   <ApplicationArea>
      <Sender>
         <LogicalID>uti</LogicalID>
         <ReferenceID>0000001299</ReferenceID>
      </Sender>
      <CreationDateTime>2017-06-20T09:54:24.217+02:00</CreationDateTime>
   </ApplicationArea>
   <DataArea>
      <Process>
         <ActionCriteria>
            <ActionExpression actionCode="ProcessUtiLoadShipped"/>
         </ActionCriteria>
      </Process>
      <Shipment>
         <ShipmentHeader>
            <DocumentID>
               <ID>0000001299</ID>
            </DocumentID>
            <DocumentDateTime>2016-12-05T13:31:09.437+01:00</DocumentDateTime>
            <ActualShipDateTime>2016-12-05T15:49:17.863+01:00</ActualShipDateTime>
            <ScheduledDeliveryDateTime>2016-12-07T13:08:00.0+01:00</ScheduledDeliveryDateTime>
            <TransportationMethodCode>20GP</TransportationMethodCode>
            <CarrierParty>
               <Name>LOGWIN</Name>
               <UserArea>
                  <TrackingID>TRAILID123</TrackingID>
                  <Note type="proNo"/>
               </UserArea>
            </CarrierParty>
            <ShipToParty>
               <Name/>
               <Location>
                  <Address>
                     <CityName>CANTERBURY</CityName>
                     <CountryCode>GB</CountryCode>
                     <PostalCode/>
                  </Address>
               </Location>
               <Contact>
                  <TelephoneCommunication>
                     <FormattedNumber/>
                  </TelephoneCommunication>
               </Contact>
            </ShipToParty>
            <Type>3</Type>
            <UserArea>
               <SealID/>
               <Note type="countryPickOrder">true</Note>
            </UserArea>
         </ShipmentHeader>
         <ShipmentUnit>
            <DocumentReference>
               <AlternateDocumentID>
                  <ID>123456-01</ID>
               </AlternateDocumentID>
               <PurchaseOrderReference>
                  <DocumentID>
                     <ID>123456</ID>
                  </DocumentID>
               </PurchaseOrderReference>
            </DocumentReference>
            <ShipmentUnitItem>
               <ItemID>
                  <ID>1000807-103-29-36</ID>
               </ItemID>
               <Specification>
                  <Property>
                     <NameValue name="ArticleNumber">1000807</NameValue>
                  </Property>
                  <Property>
                     <NameValue name="ColorCode">103</NameValue>
                  </Property>
               </Specification>
               <ShippedQuantity>4</ShippedQuantity>
               <DocumentReference>
                  <ID type="receivingNumber">0000000566B</ID>
               </DocumentReference>
               <UserArea>
                  <Note type="parcelId"/>
               </UserArea>
            </ShipmentUnitItem>
            <ShipmentUnitItem>
               <ItemID>
                  <ID>1000807-103-29-34</ID>
               </ItemID>
               <Specification>
                  <Property>
                     <NameValue name="ArticleNumber">1000807</NameValue>
                  </Property>
                  <Property>
                     <NameValue name="ColorCode">103</NameValue>
                  </Property>
               </Specification>
               <ShippedQuantity>2</ShippedQuantity>
               <DocumentReference>
                  <ID type="receivingNumber">0000000566C</ID>
               </DocumentReference>
               <UserArea>
                  <Note type="parcelId"/>
               </UserArea>
            </ShipmentUnitItem>
         </ShipmentUnit>
      </Shipment>
  </DataArea>
</ProcessShipment>
```

**Comment by javaduke** [comment]
Still not a valid mapping - the error I get is:
        (payload.*Shipment.*ShipmentUnit map
         ^
Type mismatch for 'map' operator
     found :null, :function
  required :array, :function
