### ISSUE TITLE
Error in IntelliJ opening RAML: Boolean cannot be cast to String

### ISSUE THREAD

**Issue by rmorrise** [machaval/mule-intellij-plugins#97]
```
java.lang.Boolean cannot be cast to java.lang.String
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at org.raml.yagi.framework.util.NodeSelector.selectStringValue(NodeSelector.java:99)
	at org.raml.v2.internal.impl.v10.type.ObjectResolvedType.overwriteFacets(ObjectResolvedType.java:132)
	at org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode.resolveTypeDefinition(TypeDeclarationNode.java:99)
	at org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode.getResolvedType(TypeDeclarationNode.java:85)
	at org.raml.v2.internal.impl.v10.type.ObjectResolvedType.validateCanOverwriteWith(ObjectResolvedType.java:208)
	at org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode.validateCanOverwrite(TypeDeclarationNode.java:143)
	at org.raml.v2.internal.impl.commons.phase.TypeValidationPhase.apply(TypeValidationPhase.java:39)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:114)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:93)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:116)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:100)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:95)
	at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:37)
	at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:18)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:224)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:48)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:172)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by javaduke** [comment]
Can you please post your RAML file? Or is it happening with any RAML file you are trying to open?

**Comment by rmorrise** [comment]
The attached RAML file is sufficient to reproduce the issue. The error popup only seems to appear the first time the editor is opened for that file, after starting up the IDE.

(File renamed with .TXT extension for purposes of passing GitHub upload filter)
[test.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1085195/test.raml.txt)

**Comment by rmorrise** [comment]
I don't know if it's any help, but the API Workbench plugin for the Atom text editor seems able to handle this file correctly. Not sure if it's using a different parser?

https://atom.io/packages/api-workbench

**Comment by layoaster** [comment]
I got the what it looks the same issue when I was setting `required: true` on the `uriParameters` section:

```
/{target_id}:
    uriParameters:
      target_id: integer
      required: true
      description: The id of the target opportunity to connect with.
```

Stacktrace:
```
org.raml.yagi.framework.nodes.snakeyaml.SYBooleanNode cannot be cast to org.raml.yagi.framework.nodes.StringNode
java.lang.ClassCastException: org.raml.yagi.framework.nodes.snakeyaml.SYBooleanNode cannot be cast to org.raml.yagi.framework.nodes.StringNode
	at org.raml.v2.internal.impl.v10.rules.TypeExpressionReferenceRule.apply(TypeExpressionReferenceRule.java:60)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:110)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:110)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:110)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:110)
	at org.raml.yagi.framework.grammar.rule.KeyValueRule.apply(KeyValueRule.java:171)
	at org.raml.yagi.framework.grammar.rule.ObjectRule.apply(ObjectRule.java:234)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:110)
	at org.raml.yagi.framework.grammar.rule.KeyValueRule.apply(KeyValueRule.java:171)
	at org.raml.yagi.framework.grammar.rule.ObjectRule.apply(ObjectRule.java:234)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:110)
	at org.raml.yagi.framework.grammar.rule.KeyValueRule.apply(KeyValueRule.java:171)
	at org.raml.yagi.framework.grammar.rule.ObjectRule.apply(ObjectRule.java:234)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:110)
	at org.raml.yagi.framework.grammar.rule.KeyValueRule.apply(KeyValueRule.java:171)
	at org.raml.yagi.framework.grammar.rule.ObjectRule.apply(ObjectRule.java:234)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:110)
	at org.raml.yagi.framework.grammar.rule.KeyValueRule.apply(KeyValueRule.java:171)
	at org.raml.yagi.framework.grammar.rule.ObjectRule.apply(ObjectRule.java:234)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:110)
	at org.raml.yagi.framework.grammar.rule.KeyValueRule.apply(KeyValueRule.java:171)
	at org.raml.yagi.framework.grammar.rule.ObjectRule.apply(ObjectRule.java:234)
	at org.raml.yagi.framework.phase.GrammarPhase.apply(GrammarPhase.java:38)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:114)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:93)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:116)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:100)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:95)
	at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:37)
	at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:18)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:224)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:48)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:172)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Environment:

```
PyCharm 2017.1.4
Build #PY-171.4694.38, built on June 13, 2017
JRE: 1.8.0_131-8u131-b11-0ubuntu1.17.04.1-b11 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.10.0-24-generic
```

**Comment by javaduke** [comment]
Looks like a Java parser bug after all: https://github.com/raml-org/raml-java-parser/issues/404
I'll keep this issue open till the new version of the parser released and then I'll update the plugin.
